In [1]:
import numpy as np

In [1]:
# numpy.array(
#     object, 
#     dtype = None, 
#     copy = True, 
#     order = None, 
#     subok = False, 
#     ndmin = 0
# )

In [8]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [10]:
type(a)

numpy.ndarray

In [11]:
b = np.array([[1,  2],  [3,  4]])
b

In [18]:
b.ndim

2

In [12]:
type(b)

numpy.ndarray

In [13]:
c = np.array([1,2,3,4,5], ndmin =  2) 
c

array([[1, 2, 3, 4, 5]])

In [14]:
type(c)

numpy.ndarray

In [16]:
d = np.array([1,  2,  3], dtype = complex)
d

array([ 1.+0.j,  2.+0.j,  3.+0.j])

In [17]:
type(d)

numpy.ndarray

In [21]:
w = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
w

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [22]:
w.shape

(4, 3)

In [23]:
w[0,:]

array([1, 2, 3])

In [24]:
w[1,:]

array([4, 5, 6])

In [26]:
w[1,-1]

6

In [28]:
w[1,0:2]

array([4, 5])